import face from "./assets/Image/face.jpg";

export const userData = [
    {
      name: "Jan",
      "Active User": 4000,
    },
    {
      name: "Feb",
      "Active User": 3000,
    },
    {
      name: "March",
      "Active User": 5000,
    },
    {
      name: "April",
      "Active User": 7000,
    },
    {
      name: "May",
      "Active User": 6000,
    },
    {
      name: "June",
      "Active User": 3000,
    },
    {
      name: "July",
      "Active User": 4000,
    },
    {
      name: "Aug",
      "Active User": 5000,
    },
    {
      name: "Sept",
      "Active User": 4000,
    },
    {
      name: "Oct",
      "Active User": 7000,
    },
    {
      name: "Nov",
      "Active User": 6000,
    },
    {
      name: "Dec",
      "Active User": 8000,
    },
  ];

  
  export const userRows = [
    {
      id: 1,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 2,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 3,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 4,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 5,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 6,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 7,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 8,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 9,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
    {
      id: 10,
      userName: "Snow",
      firstName: "Jon",
      avatar: face,
      email: "sourabhsikarwar1812@gmail.com",
      status: "active",
      transaction: "Rs. 1254.00",
    },
  ];
  export const productRows = [
    {
      id: 1,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 2,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 3,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 4,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 5,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 6,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 7,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 8,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 9,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
    {
      id: 10,
      name: "Apple iPod",
      firstName: "Jon",
      img: face,
      stock: 125,
      status: "active",
      price: "Rs. 1254.00",
    },
  ];